@startuml

left to right direction

actor "Visitante" as visitante

package "Interacción de Espacios"{
    usecase verEspacio as "verEspacio()"
    usecase cambiarDeEspacio as "cambiarDeEspacio()"
    usecase buscarEspacio as "buscarEspacio()"
    usecase verDetallesEspacio as "verDetallesEspacio()"
    usecase verEspaciosCercanos as "verEspaciosCercanos()"
    usecase verEspaciosPlanta as "verEspaciosPlanta()"
}

package "Interacción de Recorridos"{
    usecase listarRecorridos as "listarRecorridos()"
    usecase seleccionarRecorrido as "seleccionarRecorrido()"
}

visitante --> (verEspacio)
visitante --> (cambiarDeEspacio)
visitante --> (buscarEspacio)
visitante --> (verDetallesEspacio)
visitante --> (verEspaciosCercanos)
visitante --> (verEspaciosPlanta)

(seleccionarRecorrido) <-- visitante
(listarRecorridos) <-- visitante

@enduml