@startuml cambiarUbicacion

skinparam linetype polyline

state cambiarEspacio as "cambiarEspacio()" {

    state " " as SolicitandoCambio
    state "SeleccionandoEsapcio" as SeleccionandoEspacio
    state c <<choice>>

    [*] -[#green]-> SolicitandoCambio 
    note on link
    <b>Visitante</b> solicita cambiar 
                     su ubicación actual
    end note    
    
    SolicitandoCambio -[#green]-> SeleccionandoEsapcio
    note on link
    <b>Sistema</b> presenta
    • Opciones de ubicación
    • Mapa interactivo
    end note
    
    SeleccionandoEspacio -[#green]-> c
    note on link
    <b>Visitante</b> solicita
    • confirmar nueva ubicación
    • cancelar cambio
    end note
    
    c -[#green]-> [*]
    note on link
    confirmar / cancelar
    end note
}

cambiarEspacio -[#green]-> Explorando
note on link
regresa
end note

@enduml
