@startuml

class Campus
class Edificio
class Exterior
class Planta
class Espacio
class Parking
class Verde
class AreaDeportiva


Campus  *-- Edificio
Campus  *-- Exterior
Edificio *-- Planta
Planta  *-- Espacio
Planta o-- Parking
Exterior *-- Verde
Exterior *-- AreaDeportiva

@enduml
