@startuml

Visitante -->  Ubicación
Visitante --> Recorrido
Recorrido o-- Ubicación
Universidad  *-- Edificio
Edificio *-- Planta
Planta *-- Ubicación
Espacio -up-|> Ubicación
Pasillo -up-|> Ubicación
Entrada -up-|> Ubicación
Parking -up-|> Ubicación

@enduml
