@startuml

left to right direction

actor "Administrador" as admin

package "Gestión de Ubicaciones"{
    usecase crearUbicacion as "crearUbicacion()"
    usecase verUbicaciones as "verUbicaciones()"
    usecase eliminarUbicacion as "eliminarUbicacion()"
    usecase actualizarUbicacion as "actualizarUbicacion()"
}

package "Gestión de Recorridos"{
    usecase crearRecorrido as "crearRecorrido()"
    usecase verRecorridos as "verRecorridos()"
    usecase eliminarRecorrido as "eliminarRecorrido()"
    usecase actualizarRecorrido as "actualizarRecorrido()"
}

(crearUbicacion) <-- admin
(verUbicaciones) <-- admin
(eliminarUbicacion) <-- admin
(actualizarUbicacion) <-- admin

(crearRecorrido) <-- admin
(verRecorridos) <-- admin
(eliminarRecorrido) <-- admin
(actualizarRecorrido) <-- admin



@enduml
