@startuml

[*] --> NavegandoMenú
NavegandoMenú --> ExplorandoEdificio : Entrar
ExplorandoEdificio --> ExplorandoPlanta : Seleccionar planta
ExplorandoEdificio  --> ViendoPuntoDeInteres : Seleccionar punto de interés

ViendoPuntoDeInteres --> ExplorandoEdificio : Regresar
ExplorandoPlanta --> ExplorandoEdificio : Regresar
ExplorandoEdificio --> NavegandoMenú : Regresar

NavegandoMenú --> [*] : Salir del programa

@enduml
