@startuml

[*] --> NavegandoMenú

NavegandoMenú --> ExplorandoEdificio : Entrar
ExplorandoEdificio --> NavegandoMenú : Regresar

ExplorandoEdificio --> ExplorandoPlanta : Seleccionar planta
ExplorandoPlanta --> ExplorandoEdificio : Regresar

ExplorandoEdificio --> ViendoPuntoDeInteres : Seleccionar punto de interés
ViendoPuntoDeInteres --> ExplorandoEdificio : Regresar

NavegandoMenú --> [*] : Salir del programa

@enduml