@startuml verEspaciosCercanos

skinparam linetype polyline

state verEspaciosCercanos as "verEspaciosCercanos()" {

    state " " as SolicitandoEspaciosCercanos
    state "Consultando" as ConsultandoEspaicosCercanos
    state c <<choice>>

    [*] -[#green]-> SolicitandoEspaciosCercanos 
    note on link
    <b>Visitante</b> solicita ver espacios cercanos
    end note    
    
    SolicitandoEspaciosCercanos -[#green]-> ConsultandoEspaicosCercanos
    note on link
    <b>Sistema</b> presenta
    • lista de espacios cercanos
    end note
    
    ConsultandoEspaicosCercanos -[#green]-> c
    note on link
    <b>Visitante</b> solicita
    • continuar consultando
    • salir de espacios cercanos
    end note
    
    c -[#green]-> ConsultandoEspaicosCercanos
    note on link
    continuar consultando
    end note

    c -[#green]-> [*]
    note on link
    salir de espacios cercanos
    end note
}

verEspaciosCercanos -[#green]-> Explorando
note on link
regresa
end note

@enduml